name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android and iOS.
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in
version: 4.5.2+1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlesignin
        pluginClass: GoogleSignInPlugin
      ios:
        pluginClass: FLTGoogleSignInPlugin

dependencies:
  google_sign_in_platform_interface:
    git:
      url: https://github.com/filipproch/plugins.git
      ref: master
      path: packages/google_sign_in/google_sign_in_platform_interface
  flutter:
    sdk: flutter
  meta: ^1.0.4

dev_dependencies:
  http: ^0.12.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  e2e:
    path: ../../e2e

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
